# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Copy public assets to build
        working-directory: ./frontend
        run: |
          echo "Copying public assets to build/client..."
          cp -r public/* build/client/
          echo "Build directory contents after copying assets:"
          find build/client -type f | head -20

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./frontend/build/client"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
